
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: tvec-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/gottingen/titan-redis
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: A server based on faiss serving for vector search

source:
  git_url: ../

outputs:
  - name: titandb
    script: bld.sh   # [not win]
    script: bld.bat  # [win]
    build:
      #   string: "h{{ PKG_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('titandb', exact=True) }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - sysroot_linux-64 =2.17  # [linux64]
        - turbo
        - rocksdb
      host:
        - sysroot_linux-64 =2.17  # [linux64]
        - turbo
        - rocksdb
      run:
        - sysroot_linux-64 =2.17  # [linux64]
        - turbo
        - rocksdb
    test:
      commands:
        - test -f $PREFIX/lib/libtitandb.so              # [linux]
        - test -f $PREFIX/lib/libtitandb.dylib           # [osx]
      #  - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
      #  - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
